### ISSUE TITLE
ICA Aroma strategy 

### ISSUE THREAD

**Issue by Yvonneser** [SIMEXP/load_confounds#156]
Hey, @pbellec  @htwangtw  I have one question :
did this strategy use the MELODIC_mixing.tsv file or the _timeserice.tsv file (fmriprep outputs) 
and should I recalculate the WM and the CSF regarding to this issue (https://github.com/nipreps/fmriprep/issues/1905) ? 

Best regards 
Yvonne

**Comment by htwangtw** [comment]
First of all, I would suggest to use the current nilearn implementation instead of this repository, and ask questions related to general usage and literature to [neurostars](https://neurostars.org/) so more people can see it. As this is not related to the code base, I will close it with the answer below. 

The ICA-AROMA strategy used  AROMA-cleaned data (`~desc-smoothAROMAnonaggr_bold.nii.gz`) instead of the regressors.
For details of the implementation please see the doc string of related function.

Please see fMRIprep documentation for the WM and CSF related issue:

> Additionally, as per [[Hallquist2013]](https://fmriprep.org/en/stable/outputs.html#hallquist2013) and [[Lindquist2019]](https://fmriprep.org/en/stable/outputs.html#lindquist2019), when using AROMA-cleaned data most of the confound regressors should be recalculated (this feature is a work-in-progress, follow up on [#1905](https://github.com/nipreps/fmriprep/issues/1905)). Surprisingly, [our simulations](https://github.com/nipreps/fmriprep-notebooks/blob/9933a628dfb759dc73e61701c144d67898b92de0/05%20-%20Discussion%20AROMA%20confounds%20-%20issue-817%20%5BJ.%20Kent%5D.ipynb) (with thanks to JD. Kent) suggest that using the confounds as currently calculated by fMRIPrep –before denoising– would be just fine.
