### ISSUE TITLE
re-write tests in a more compact format

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#27]
The tests currently are a long list of variations on the same snippet, combining certain parameters. It would be possible to replace all the test by one nested for loop, with a list of parameters to be tested, and a list of expected confound labels associated with each parameter.

**Comment by HanadS** [comment]
Thanks for the comment @pbellec . I'm not sure adding a for loop would be best because later when a test fails it won't be obvious which combination of parameters that failed (not that it's impossible to find out). 

https://stackoverflow.com/questions/41832594/should-you-do-an-assert-statement-inside-a-loop

So what I have done for now is placed all of the output in json files so that the .py files look a little more clean.

**Comment by pbellec** [comment]
Unfortunately I don't think those tests are useful. 

Hard-coding the outputs means that any error is hard-coded. All you can conclude if the test fails is that something has changed, but you can't learn if it's a good or a bad thing.

there are also so many tests, and the data is so complex, that understanding a test failure is going to be serious forensic work. 

I am going to start a test suite to get you a feel of what it could look like.

**Comment by pbellec** [comment]
Now test suite  addressed that issue.
